### ISSUE TITLE
Access response body when UnprocessableEntity is raised

### ISSUE THREAD

**Issue by gulazaro94** [leadmachineapp/simple_spark#17]
First of all, thanks for this amazing gem with very good documentation.

I would like to add a new feature and first I'd like to ask if it makes sense or not.

I am having a situation when I create a transmission with inline recipient and one of the recipient is invalid.
The SP returns a 422 and the gem raises an UnprocessableEntity exception. SP creates the transmission and need to threat this case. In this exception I can access the only the node `errors` through the method `object`. But I need to know the amount of accpeted_recipients, rejected_recipients, etc.

My proposal is only to add the response_body to be accessible on the exception too.
I wouldn't change any of the actual API so there is no need to change the code when upgrade.

If you say ok, I will fork and create the PR.

Best regards from Brazil.

**Comment by jakcharlton** [comment]
Seems like a good idea, I never needed to deal with more than the status, so never added this originally

**Comment by zainzafar** [comment]
I think https://github.com/leadmachineapp/simple_spark/pull/19 would solve that

**Comment by gulazaro94** [comment]
That's exactly what I would do, perfect. :)
