### ISSUE TITLE
RubyGems.org is outdated

### ISSUE THREAD

**Issue by zainzafar** [leadmachineapp/simple_spark#20]
It appears the latest code changes don't reflect using the following in the bundle file:
`gem 'simple_spark'`
```ruby
irb(main):004:0> SimpleSpark::Exceptions::Error.fail_with_exception_for_status('default', ['Error message'], {transmission_id: 123})
ArgumentError: wrong number of arguments (given 3, expected 2)
```

**Comment by jakcharlton** [comment]
Not all incremental changes are pushed as gen releases 

This one probably should be, but in the meantime you can specify the commit from master in your gemfile

**Comment by zainzafar** [comment]
Yup I agree. I'm using direct `master` for now

**Comment by jakcharlton** [comment]
Updated rubygems to 1.0.6
https://rubygems.org/gems/simple_spark
