### ISSUE TITLE
May want to give an example of transmission with template referenced in documentation

### ISSUE THREAD

**Issue by jump3r34** [leadmachineapp/simple_spark#26]
I thought this would help for those looking at implementing this gem (which I think is the best and most versitile sparkpost gem for rails, and it works with rails 6.0 so you will see quite a few people migrating over to it).  I also fixed the broken <p> tag in the html section of the content which was causing a run-on line when testing the method/call.

``` ruby
# with content in call
properties = {
  options: { open_tracking: true, click_tracking: true },
  campaign_id: 'christmas_campaign',
  return_path: 'bounces-christmas-campaign@sp.neekme.com',
  metadata: {user_type: 'students'},
  substitution_data: { sender: 'Big Store Team', address: '123 Your Road' },
  recipients:  [
    { address: { email: 'yourcustomer@theirdomain.com', name: 'Your Customer' },
      tags: ['greeting', 'sales'],
      metadata: { place: 'Earth' }, substitution_data: { address: '123 Their Road' } }
  ],
  content:
  { from: { name: 'Your Name', email: 'you@yourdomain.com' },
    subject: 'I am a test email',
    reply_to: 'Sales <sales@yourdomain.com>',
    headers: { 'X-Customer-CampaignID' => 'christmas_campaign' },
    text: 'Hi from {{sender}} ... this is a test, and here is your address {{address}}',
    html: '<p>Hi from {{sender}}</p><p>This is a test</p>'
  }
}
# calling a template by id in the content section
properties = {
    options: { open_tracking: true, click_tracking: true },
    campaign_id: 'christmas_campaign',
    return_path: 'bounces-christmas-campaign@sp.neekme.com',
    metadata: {user_type: 'students'},
    substitution_data: { sender: 'Big Store Team', address: '123 Your Road' },
    recipients:  [
        { address: { email: 'yourcustomer@theirdomain.com', name: 'Your Customer' },
          tags: ['greeting', 'sales'],
          metadata: { place: 'Earth' }, substitution_data: { address: '123 Their Road' } }
    ],
    content: { template_id: 'first-template-id' }
}

**Comment by jakcharlton** [comment]
Hi @jump3r34 ... I'm a little unclear about what you have changed here. Could you provide a pull request if you think there's a mistake somewhere? Or identify which bit of code is wrong?

Also, would be happy to accept any pull requests with better (or more) examples, as we only use a small part of the API so many are theoretical only

**Comment by jump3r34** [comment]
On Transmissions/Create a new transmission, on the readme and commented in the transmissions file as well is a line in the content which is the html missing a closing tag:
``` ruby
html: '<p>Hi from {{sender}}</p<p>This is a test</p>'
```
I changed to this:
``` ruby
html: '<p>Hi from {{sender}}</p><p>This is a test</p>'
```
Then (my post above) everything after #calling a template by id in the content section is an extra 'create transmission' example that is using a template (rather than injected text and html in the content). The templates are made in the sparkpost admin area already (since many people already have templates with dynamic data areas already built) and this is the way to call it by it's id. I tried to keep everything else the same in your properties object while just changing the content to take the already built template that use may want to call.

**Comment by jakcharlton** [comment]
Ahhh cool - spotted it thanks!

**Comment by jump3r34** [comment]
Not a problem at all.  

This is really the best sparkpost gem out there.  I have a feeling a lot more people will be using it with rails 6 since it keeps it down at the wrapper level and doesn't need many dependencies.

Thanks for a great gem!

**Comment by jakcharlton** [comment]
@jump3r34 made the changes, bumped the version https://rubygems.org/gems/simple_spark/versions/1.0.11
