### ISSUE TITLE
Include tag names in releases

### ISSUE THREAD

**Issue by dmitry** [leadmachineapp/simple_spark#3]
For easier tracking down the changes it would be nice to include tag names for each release inside the https://github.com/leadmachineapp/simple_spark/releases.

**Comment by jakcharlton** [comment]
Probably wise, not being an expert in this, how would you suggest it's best done?

**Comment by dmitry** [comment]
@jakcharlton normally you need to add `require 'bundler/gem_tasks'` to the `Raketask` and run `rake release` once you are releasing the gem to the rubygems. It will create tag and build and push gem to Rubygems.

**Comment by jakcharlton** [comment]
Cheers @dmitry , I've been using the old fashioned gem build and gem push commands, Github being a bit of an afterthought - Ill look into using rake release :)
