### ISSUE TITLE
Join forces to get better sparkpost API wrapper for ruby

### ISSUE THREAD

**Issue by dmitry** [leadmachineapp/simple_spark#5]
First I tried https://github.com/SparkPost/ruby-sparkpost gem and then I found `simple_spark` and it looks more advanced and more ruby-idiomatic. I suggest you guys to join forces and build one, but better sparkpost API wrapper.

Lets find the way to join forces on https://github.com/SparkPost/ruby-sparkpost/issues/42

PS. I'm not related to the sparkpost, I just want to make the OSS better.

**Comment by jakcharlton** [comment]
Due to SP deciding to discontinue their gem, simple_spark has been pushed to version 1.0 as it has now been stable some time in production. It’s probably not as well tested as I would like, but as it’s now the best Ruby option there’s not much choice for us Ruby users.

**Comment by dmitry** [comment]
@jakcharlton thanks for noticing! Great that it happened, better to have just 1 gem that everyone is using and supporting...
