### ISSUE TITLE
SparkPost Specific Error Codes 

### ISSUE THREAD

**Issue by kyleboe** [leadmachineapp/simple_spark#7]
I have been looking at how [simple_spark handles exceptions](https://github.com/leadmachineapp/simple_spark/blob/master/lib/simple_spark/exceptions.rb) and error code reporting and want to make sure that I am not missing anything. [The old SparkPost maintained Gem](https://github.com/SparkPost/ruby-sparkpost/blob/master/lib/sparkpost/exceptions.rb#L11) would return an [error code specific to SparkPost](https://support.sparkpost.com/customer/en/portal/articles/2140916-extended-error-codes). I need to raise errors based on the various responses with these specific codes (e.g. handle `3001 substitution render error` differently than `3002 Invalid header` whereas they both return a 422 HTTP Status Code). 

I can see that the code/message is passed into the response

``` ruby
#<Excon::Response:0x007fd0f989e230 @data={:body=>"{ \"errors\": [ { \"message\": \"At least one valid recipient is required\", \"code\": 5002 } ] }", :headers=>{"Cache-Control"=>"no-cache, no-store", "Content-Type"=>"application/json", "Date"=>"Wed, 25 May 2016 21:27:35 GMT", "Server"=>"msys-http", "Vary"=>"Accept", "Content-Length"=>"89", "Connection"=>"keep-alive"}, :status=>400, :status_line=>"HTTP/1.1 400 Bad Request\r\n", :reason_phrase=>"Bad Request", :remote_ip=>"goes here", :local_port=>54590, :local_address=>"192.168.1.159"}, @body="{ \"errors\": [ { \"message\": \"At least one valid recipient is required\", \"code\": 5002 } ] }", @headers={"Cache-Control"=>"no-cache, no-store", "Content-Type"=>"application/json", "Date"=>"Wed, 25 May 2016 21:27:35 GMT", "Server"=>"msys-http", "Vary"=>"Accept", "Content-Length"=>"89", "Connection"=>"keep-alive"}, @status=400, @remote_ip="goes here too", @local_port=54590, @local_address="192.168.1.159">
```

Is there a good way to get at that code (in the above case, 5002)?

**Comment by jakcharlton** [comment]
There isn't an easy way

Sparkposts API is a bit of a mess like that, it throws massive numbers of
errors, most of which can be treated the same, hence why simple_spark
condenses them to just a few so the client app doesn't have to deal with so
many code paths

I wouldn't want to create more exception classes, but would be happy to
have the code put into the exception message if you wanted to submit a pull
request for that?

Something like :

"#{message} (code: #{code})"

You could then catch the general exception and refer the message

It guess it could be added as a field onto the exception classes too but
I'm less find of this approach

**Comment by kyleboe** [comment]
Sounds good. Yeah I agree completely, more Exception classes is not the way to go. I will make a PR here shortly with the slight message change. Thanks for the response.
